name: my_delivery_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - asset/img/food/
    - asset/img/logo/
    - asset/img/misc/
    - asset/rive/
  uses-material-design: true

font:
  - family: NotoSans
    fonts:
      - asset: asset/fonts/NotoSansKR-Black.otf
        weight: 900
      - asset: asset/fonts/NotoSansKR-Bold.otf
        weight: 700
      - asset: asset/fonts/NotoSansKR-Medium.otf
        weight: 500
      - asset: asset/fonts/NotoSansKR-Regular.otf
        weight: 400
      - asset: asset/fonts/NotoSansKR-Light.otf
        weight: 300
      - asset: asset/fonts/NotoSansKR-Thin.otf
        weight: 100
