name: my_delivery_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2

  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  retrofit_generator: '>=7.0.0 <8.0.0'   # required dart >=2.19
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  assets:
    - asset/img/food/
    - asset/img/logo/
    - asset/img/misc/
    - asset/rive/
  uses-material-design: true

fonts:
  - family: NotoSans
    fonts:
      - asset: asset/fonts/NotoSansKR-Black.otf
        weight: 900
      - asset: asset/fonts/NotoSansKR-Bold.otf
        weight: 700
      - asset: asset/fonts/NotoSansKR-Medium.otf
        weight: 500
      - asset: asset/fonts/NotoSansKR-Regular.otf
        weight: 400
      - asset: asset/fonts/NotoSansKR-Light.otf
        weight: 300
      - asset: asset/fonts/NotoSansKR-Thin.otf
        weight: 100
